# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x08messages\"\x1d\n\x0cQueryMessage\x12\r\n\x05query\x18\x01 \x01(\t\"\x1e\n\x0fResponseMessage\x12\x0b\n\x03res\x18\x01 \x01(\t2R\n\x0eMessageService\x12@\n\x0bsendMessage\x12\x16.messages.QueryMessage\x1a\x19.messages.ResponseMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYMESSAGE']._serialized_start=28
  _globals['_QUERYMESSAGE']._serialized_end=57
  _globals['_RESPONSEMESSAGE']._serialized_start=59
  _globals['_RESPONSEMESSAGE']._serialized_end=89
  _globals['_MESSAGESERVICE']._serialized_start=91
  _globals['_MESSAGESERVICE']._serialized_end=173
# @@protoc_insertion_point(module_scope)
